name: notesapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: 2.27.1
  firebase_auth: 4.17.8
  cloud_firestore: 4.15.3

  google_sign_in: 6.1.5
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  flutter_svg: ^2.2.2
  image_picker: ^1.2.1
  image: ^4.5.4
  intl: ^0.20.2
  flutter_slidable: ^4.0.3
  flutter_quill: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/